[package]
name = "spoiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adw = { version = "0.4.1", package = "libadwaita" }
gtk = { version = "0.6.6", package = "gtk4", features = ["v4_10", "blueprint"] }
log = "0.4.17"
